package com.practice.mybatis.model;

public class HumanRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column human_relation.id
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column human_relation.relation_name
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    private String relationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column human_relation.stage
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    private String stage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column human_relation.target
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    private String target;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column human_relation.maintain
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    private String maintain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human_relation.id
     *
     * @return the value of human_relation.id
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human_relation.id
     *
     * @param id the value for human_relation.id
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human_relation.relation_name
     *
     * @return the value of human_relation.relation_name
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public String getRelationName() {
        return relationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human_relation.relation_name
     *
     * @param relationName the value for human_relation.relation_name
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public void setRelationName(String relationName) {
        this.relationName = relationName == null ? null : relationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human_relation.stage
     *
     * @return the value of human_relation.stage
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public String getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human_relation.stage
     *
     * @param stage the value for human_relation.stage
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public void setStage(String stage) {
        this.stage = stage == null ? null : stage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human_relation.target
     *
     * @return the value of human_relation.target
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human_relation.target
     *
     * @param target the value for human_relation.target
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column human_relation.maintain
     *
     * @return the value of human_relation.maintain
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public String getMaintain() {
        return maintain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column human_relation.maintain
     *
     * @param maintain the value for human_relation.maintain
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    public void setMaintain(String maintain) {
        this.maintain = maintain == null ? null : maintain.trim();
    }
}