package com.practice.mybatis.model;

public class Woman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column woman.id
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column woman.name
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column woman.age
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column woman.height
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    private Integer height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column woman.weight
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column woman.id
     *
     * @return the value of woman.id
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column woman.id
     *
     * @param id the value for woman.id
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column woman.name
     *
     * @return the value of woman.name
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column woman.name
     *
     * @param name the value for woman.name
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column woman.age
     *
     * @return the value of woman.age
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column woman.age
     *
     * @param age the value for woman.age
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column woman.height
     *
     * @return the value of woman.height
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column woman.height
     *
     * @param height the value for woman.height
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column woman.weight
     *
     * @return the value of woman.weight
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column woman.weight
     *
     * @param weight the value for woman.weight
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}