package com.practice.mybatis.dao;

import com.practice.mybatis.model.Woman;
import com.practice.mybatis.model.WomanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WomanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    long countByExample(WomanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    int deleteByExample(WomanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    int insert(Woman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    int insertSelective(Woman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    List<Woman> selectByExample(WomanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    Woman selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") Woman record, @Param("example") WomanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    int updateByExample(@Param("record") Woman record, @Param("example") WomanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    int updateByPrimaryKeySelective(Woman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table woman
     *
     * @mbg.generated Sat Sep 01 21:39:58 CST 2018
     */
    int updateByPrimaryKey(Woman record);
}