server:
  port: 8081

spring:
  application:
    name: mybatis-practice
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sakila?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
mybatis:
  configuration:
    default-statement-timeout: 3  # seconds
    map-underscore-to-camel-case: true
  type-handlers-package: com.practice.mybatis.repository.verifyjsonconvert.typehandler
#  type-aliases-package: com.practice.mybatis.model
#若mapper xml与mapper接口共包，则不需要配置;
#  mapper-locations:
#    - classpath:com/practice/mybatis/dao/**/*.xml
#    - classpath:com/practice/mybatis/repository/**/*.xml
logging:
  level:
    com.practice.mybatis.repository: debug
