spring:
  application:
    name: mybatis-practice
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis_practice
    password: root
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
mybatis:
  configuration:
    default-statement-timeout: 30
  type-aliases-package: com.practice.mybatis.model
  mapper-locations: classpath:com/practice/mybatis/dao/**/*.xml