package com.practice.mybatis.repository.sakila;

import com.practice.mybatis.ao.QueryRequest;
import com.practice.mybatis.repository.sakila.entity.Actor;
import java.util.List;

public interface ActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Thu Nov 21 14:33:45 CST 2019
     */
    int deleteByPrimaryKey(Short actorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Thu Nov 21 14:33:45 CST 2019
     */
    int insert(Actor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Thu Nov 21 14:33:45 CST 2019
     */
    Actor selectByPrimaryKey(Short actorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Thu Nov 21 14:33:45 CST 2019
     */
    List<Actor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table actor
     *
     * @mbg.generated Thu Nov 21 14:33:45 CST 2019
     */
    int updateByPrimaryKey(Actor record);


    List<Actor> selectAllShard(QueryRequest request);
    List<Actor> selectAllShard1(QueryRequest request);
    List<Actor> selectAllShard2(QueryRequest request);
    List<Actor> selectAllShard3(QueryRequest request);

}
