package com.practice.mybatis.repository.human;

import com.practice.mybatis.repository.human.entity.HumanRelation;
import java.util.List;

public interface HumanRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human_relation
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human_relation
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    int insert(HumanRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human_relation
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    HumanRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human_relation
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    List<HumanRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table human_relation
     *
     * @mbg.generated Mon Sep 03 10:39:11 CST 2018
     */
    int updateByPrimaryKey(HumanRelation record);
}